### ISSUE TITLE
[QUESTION] Calibrate and tune LFXO Capacitor Bank (CMU clock) in firmware for ITead Zigbee 3.0 USB Dongle Model 9888010100045 with hardware v1.3?

### ISSUE THREAD

**Issue by Hedda** [xsp1989/zigbeeFirmware#10]
Note! This is a follow up to https://github.com/xsp1989/zigbeeFirmware/issues/4 as a separate issue so the other can be closed separately when resolved.

Does the LFXO Capacitor Bank (CMU clock) also have to be calibrated/tuned and the current tune/tuning value set for that as well in the firmware for ITead Zigbee 3.0 USB Dongle Model 9888010100045 with hardware version 1.3 or?

https://www.silabs.com/community/mcu/32-bit/forum.topic.html/clibrate_lfxo_inefr-3I0T

https://www.silabs.com/community/mcu/32-bit/forum.topic.html/how_do_i_use_thetun-Pqlx

https://www.silabs.com/community/mcu/32-bit/forum.topic.html/how_to_improve_lfxoaccuracyinbgm13p22-v4qc

They reference to: 

https://www.silabs.com/documents/public/application-notes/an0004.2-efr32-series2-cmu.pdf

and

https://www.silabs.com/documents/public/application-notes/an0004.1-efm32-cmu.pdf

All these manufacturing tests have not yet been done or?

https://www.silabs.com/documents/public/application-notes/an700-1-mfg-test-guidelines-efr32.pdf

PS: Read about LFXO in KB article below "_This KBA focuses only to HFXO calibration **but the LFXO has its own capacitor bank.**_"

https://www.silabs.com/community/wireless/proprietary/knowledge-base.entry.html/2019/03/18/hfxo_capacitor_bank-7uRt

**Comment by Hedda** [comment]
Might this also be related to issues reported in https://github.com/home-assistant/core/issues/48592 ?

**Comment by xsp1989** [comment]
The firmware does not use LFXO （low frequency crystal oscillator）and does not require calibration。
