### ISSUE TITLE
"touchlink" (touchlinking) support enabled in current firmware images?

### ISSUE THREAD

**Issue by Hedda** [xsp1989/zigbeeFirmware#26]
@xsp1989 Can you please confirm is your firmware for SM-011/ZYZBP008/ZB-GW04, etc. support "touchlink" (touchlinking) support?

https://www.zigbee2mqtt.io/guide/usage/touchlink.html

Question about ezsp adapter touchlink for Zigbee Light Link (ZLL) devices was brought up here -> https://github.com/Koenkk/zigbee-herdsman/issues/319

kirovilya then wrote in this other thread that the current firmware for ITead's new "ZBDongle-E" does not have Touchlink support enabled in firmware but that the ezsp adapter for zigbee-herdsman/Zigbee2MQTT/IoBroker does support touchlink and touchlinking functionality does work on other efr32 adapters:

https://github.com/Koenkk/zigbee2mqtt/discussions/13893

_Originally posted by @kirovilya in https://github.com/Koenkk/zigbee2mqtt/discussions/13893#discussioncomment-3591453_

> **_I know that in other dongles on efr32, the touchlink functionality works. But in the firmware for sonoff dongle-e it is disabled (according to my information). To make it work - you need another firmware (I don’t know which one yet)._**

**Comment by xsp1989** [comment]
hi @Hedda In the latest firmware, touch link has been enabled.But default parameters are not necessarily the best.
Someone has been successfully paired
https://github.com/Koenkk/zigbee-herdsman/issues/319#issuecomment-1241133124
