### ISSUE TITLE
Sonoff Zigbee Bridge As Router - Maximum 6 devices can be paired

### ISSUE THREAD

**Issue by ZamliyMedre** [xsp1989/zigbeeFirmware#30]
It seems we can only pair maximum of 6 devices with the Sonoff Zigbee Bridge flashed with the router firmware "efr32mg21_zigbee_router_signed-6.7.10.gbl.ota".

I currently have 1 Sonoff Zigbee Bridge (coordinator) and 2 Sonoff Zigbee Bridges flashed with router firmware mentioned above. Both routers successfully paired with the coordinator, but it seems I can only add maximum of 6 devices per router.

I have tried both Zigbee2Mqtt and Home Assistant ZHA, same results. After pairing the 6th device, it is not possible to pair any more with the target router. Nothing created in the logs for both Zigbee2Mqtt or HASSIO ZHA Integration during pairing it just times out for both.

Same hardware running with the Tasmota bridge firmware can support more than 6 child devices, for that not sure why we can only add maximum of 6 devices when running with the router firmware.

Any help to resolve the issue would be very much appreciated.

Many Thanks

Erdem

**Comment by xsp1989** [comment]
Thank you very much for your feedback, the firmware on google driver may be the firmware compiled earlier, it should be the default 6 dormant devices, and now the firmware that supports 32 sub-devices has been updated：

https://github.com/xsp1989/zigbeeFirmware/tree/master/firmware/ZigbeeBridge_SM-011-signed/Router-Singed

**Comment by ZamliyMedre** [comment]
Hi

Thank you for the update however I am having difficulty apply the updated firmware, Tasmota reporting invalid file signature, what am I doing wrong ? any help would be very much appreciated.

<img width="475" alt="Screenshot 2022-11-18 at 10 27 52" src="https://user-images.githubusercontent.com/64253821/202681688-9a7e7478-3baa-4f90-9ae5-9626a96d77a5.png">
<img width="475" alt="Screenshot 2022-11-18 at 10 26 32" src="https://user-images.githubusercontent.com/64253
<img width="475" alt="Screenshot 2022-11-18 at 10 28 35" src="https://user-images.githubusercontent.com/64253821/202681758-d82c9d9d-a97f-40e3-ab45-c073cb2e8091.png">
821/202681727-af77c61d-1220-42a8-bc72-697c04cae992.png">

**Comment by ZamliyMedre** [comment]
Thank you very much @xsp1989 for the updated firmware!

I have tried to update the firmware on the existing Tasmota Sonoff Zigbee Router but this failed with "Invalid File Signature" error.

After some investigation it turns out you have to first flash the router with the tasmota-zbridge firmware > change the module type to "Sonoff ZBbridge (75)" after you can update the new firmware.

For visibility I have captured some screenshots for anyone had the same issue as me as a step-by-step guide to update already flashed Tasmota Sonoff Zigbee Router.

<img width="475" alt="Screenshot 2022-11-18 at 11 07 09" src="https://user-images.githubusercontent.com/64253821/202696923-c1f2174b-62a8-447e-9d81-24bbb7ff25df.png">

Change OTA url to : http://ota.tasmota.com/tasmota/release/tasmota-zbbridge.bin.gz

Click "Start Upgrade"

<img width="475" alt="Screenshot 2022-11-18 at 11 10 26" src="https://user-images.githubusercontent.com/64253821/202697190-4e3cac26-9344-4cee-844e-090d7961504e.png">

<img width="475" alt="Screenshot 2022-11-18 at 11 11 25" src="https://user-images.githubusercontent.com/64253821/202697240-b541574f-4945-4c75-bf1f-ff99ab7b3065.png">

After device reboots, Click "Configuration"

<img width="475" alt="Screenshot 2022-11-18 at 11 13 52" src="https://user-images.githubusercontent.com/64253821/202697351-a3fa94e7-035d-4d3f-94cd-693fb3a631c4.png">

Click "Configure Module" option

<img width="475" alt="Screenshot 2022-11-18 at 11 14 24" src="https://user-images.githubusercontent.com/64253821/202697501-0bd3d746-bbca-44a3-8caa-034b945d4e38.png">

Select "Sonoff ZBbridge (75)" from drop down list, and click "Save"

<img width="475" alt="Screenshot 2022-11-18 at 11 15 14" src="https://user-images.githubusercontent.com/64253821/202697644-1a093bb1-f670-4e99-8355-d7e2ec5bd7ea.png">

<img width="475" alt="Screenshot 2022-11-18 at 11 16 09" src="https://user-images.githubusercontent.com/64253821/202697744-d1a82375-a0ce-432d-8d7c-c95248b46f9d.png">

After device reboots, Click "Firmware Upgrade"

<img width="475" alt="Screenshot 2022-11-18 at 11 16 23" src="https://user-images.githubusercontent.com/64253821/202697817-2471ab53-1df8-488a-983c-661a358380f6.png">

Under "Update firmware by File Section", Select "Choose File" option to browse to the new firmware file downloaded.
Click "Start Upgrade"

<img width="475" alt="Screenshot 2022-11-18 at 11 17 12" src="https://user-images.githubusercontent.com/64253821/202698031-016fdfdb-3be6-49c8-a40e-c06e30babf1a.png">

<img width="475" alt="Screenshot 2022-11-18 at 11 18 28" src="https://user-images.githubusercontent.com/64253821/202698067-fc1a28c5-e7ba-4748-a057-f73ebbf5a6b5.png">

<img width="475" alt="Screenshot 2022-11-18 at 11 19 16" src="https://user-images.githubusercontent.com/64253821/202698090-13b068df-b03f-4539-9917-2c40c5031ea6.png">

After device reboots, Click "Consoles"

<img width="475" alt="Screenshot 2022-11-18 at 11 19 33" src="https://user-images.githubusercontent.com/64253821/202698188-c51fd6c0-8925-41e7-bcd9-7da7a34a33fc.png">

Click "Console"

<img width="475" alt="Screenshot 2022-11-18 at 11 20 12" src="https://user-images.githubusercontent.com/64253821/202698269-9f30cf1d-c441-41c0-a317-8e6c35b51fa8.png">

Paste the following command to the text box and hit "Enter / Return Key"

backlog template {"NAME":"Sonoff ZigRouter","GPIO":[320,5088,0,5120,257,256,0,0,0,576,0,0,32,0],"FLAG":0,"BASE":18} ; delay1 ; module 0

<img width="1659" alt="Screenshot 2022-11-18 at 11 21 02" src="https://user-images.githubusercontent.com/64253821/202698466-be01042d-737f-4aad-b9c5-e46b517f96a0.png">

Wait for the device to restart, Click "Consoles" to go back to previous menu

<img width="1659" alt="Screenshot 2022-11-18 at 11 32 57" src="https://user-images.githubusercontent.com/64253821/202698547-774d8606-1c14-40d2-b5c4-53749e0ec852.png">

Click "Main Menu" to go back to previous menu

<img width="460" alt="Screenshot 2022-11-18 at 11 33 28" src="https://user-images.githubusercontent.com/64253821/202698686-0e3f8df8-0b6a-461e-8bb1-f8163da98528.png">

Finally reboot the device again to complete upgrade.

<img width="460" alt="Screenshot 2022-11-18 at 11 34 01" src="https://user-images.githubusercontent.com/64253821/202698801-b6452f81-d192-4f7b-ac84-22b91afde402.png">

**Comment by ZamliyMedre** [comment]
@xsp1989 thanks again for updating the firmware, I have now successfully paired all Aqara Zigbee devices with Sonoff Zigbee Routers.

If anyone having issues with dropped Aqara door / window sensors especially the older model 11LM with temperature sensors built-in .. here is what I have done to keep them stick to Zigbee Router.

1. Get Sonoff USB Zigbee dongle plug that directly to the USB port of your device where HASSIO is running
2. HASSIO will detect it and ask you to install ZHA integration...
3. Start pairing new Sonoff Zigbee Routers, by pairing first one closest to the USB Coordinator.
4. than pair any other Sonoff Zigbee Routers by using the previous router you have paired so you basically daisy chain the Sonoff Routers...by distance.
5. If you have Aqara door sensors, these thing don't have great range for that you need to me maximum 7-10m away from the Zigbee Router, but first pair them right next to the Sonoff Router than you can put them in their permanent place. Make sure you select the relevant router closer to the sensor your pairing and enabling pairing on that router. This is very important as Aqara sensors do not like to roam and they stick to the initial coordinator / router they are paired to.
6. Gradually pair the rest of Aqara sensors according to the distance they are to the routers you may have.
7. Finally add any other Zigbee devices, again by using closest router to that device.

I hope this helps to other who had bad luck with the Aqara sensors.

Here is a screen shot of my Zigbee network with 43 devices, where I have 21 Aqara door /window sensors (11LM).

<img width="1670" alt="Screenshot 2022-11-18 at 23 16 36" src="https://user-images.githubusercontent.com/64253821/202819850-0fbd1b57-9a79-49f0-8a29-d406b4af8452.png">

**Comment by MattWestb** [comment]
@ZamliyMedre If you like after adding your backbone of rosters you can blocking the coordinator having direct children (end device cant using it and must using other routers) by adding this line in HA config under ZHA `      CONFIG_MAX_END_DEVICE_CHILDREN: 0` and restarting HA or the integration but you mus making it larger then zero if you is restarting from scratch for adding the first router or it cant joining.

Great work done !!
