### ISSUE TITLE
Hardware settings of ZB-GW04 

### ISSUE THREAD

**Issue by MattWestb** [xsp1989/zigbeeFirmware#34]
Sorry for pinging you @xsp1989 then you is not working for Sonoff longer.
I have on technical question. You was saying that the ZB-GW04 is having PCB lines for hardware flow control but i was not asking for the pin / pads used in both ends.
We have one user that is trying (successfully) cooking RCP firmware for that hardware and its better if we can getting the HW flow control working for getting stable communication with the RCP.

If you have time and knowledge your replay is more then welcome and if not its very OK.

All the best for you !!

Mattias W

**Comment by xsp1989** [comment]
ZB-GW04 is designed and produced by easyiot, CTS/RTS is only supported by the latest hardware version, and the hardware version is v1.3.

**Comment by MattWestb** [comment]
Is you knowing and can sharing witch pins ( pads is using for CTS / RTS ?


Thanks in advance.

**Comment by xsp1989** [comment]
![d8914012d5b7db1995686c8737f58cc](https://user-images.githubusercontent.com/24888398/215101076-6f0fae22-61b6-4573-a19a-6283ce27ca8d.jpg)

PD03-RTS
PD04-CTS

**Comment by MattWestb** [comment]
Great thanks also for all support you have done for the community !!

Mattias W
