### ISSUE TITLE
[QUESTION] ZB-GW04 USB VID + PID + unique description string?

### ISSUE THREAD

**Issue by Hedda** [xsp1989/zigbeeFirmware#40]
@xsp1989 Do you know if ZB-GW04 USB VID + PID? + does it have a unique description string written to EEPROM of USB chip?

USB VID + PID + unique description string is needed for automatic USB discovery in Home Assistant's ZHA integration:

https://community.home-assistant.io/t/community-help-wanted-to-whitelist-all-compatible-zigbee-and-z-wave-dongles-adapters-for-automatic-usb-discovery-in-home-assistant/344412

https://github.com/home-assistant/core/blob/dev/homeassistant/components/zha/manifest.json

https://www.home-assistant.io/integrations/zha#discovery-via-usb-or-zeroconf

https://www.home-assistant.io/integrations/usb/

PS: I don't have one myself but someone wrote ZB-GW04 v1.2 USB uses the identifier 1A86:7523 which should be VID and PID:

https://community.home-assistant.io/t/zigbee-coordinator-1a86-7523-cannot-start-or-pair-any-devices/545740

If that is correct then the question remains if it also has a unique description string written to EEPROM of USB chip or not?

PPS: 1A86:7523 is not unique so it will also need a custom description string written to EEPROM of USB chip for unique detection.

**Comment by xsp1989** [comment]
![image](https://user-images.githubusercontent.com/24888398/231776107-084def8e-6e9e-420f-b6ed-df040806788f.png)

VID = 1A86 PID = 7523

**Comment by Hedda** [comment]
@xsp1989 No custom USB description string written?  ...I believe that only CH340B in the CH340 series features an EEPROM(?)

**Comment by xsp1989** [comment]
The model we use is CH340E, this chip does not support configuration

Software  supports:  CH340B,  CH343P,  CH342F,  CH347T,  CH344Q/L,  CH348Q/L,  CH9
101U/H/R/Y,  CH9102F,  CH9103M,  CH9104L
