### ISSUE TITLE
Request router FW for Sonoff Zigbee 3.0 USB Dongle Plus (Model "ZBDongle-E" with EFR32MG21 chip)

### ISSUE THREAD

**Issue by tomtzeng** [xsp1989/zigbeeFirmware#43]
current router FW efr32mg21_zigbee_router_6.7.10.gbl can't work on Sonoff Zigbee 3.0 USB Dongle Plus (Model "ZBDongle-E" with EFR32MG21 chip)
have any chance to support it? event use new SDK version for router firmware?

**Comment by xsp1989** [comment]
Although ZB-GW04 has similar hardware to Sonoff Zigbee 3.0 USB Dongle Plus, we cannot guarantee that our firmware can run normally on Sonoff’s dongle, so you can use Sonoff’s open firmware, we will not provide dedicated firmware for Sonoff support

**Comment by tomtzeng** [comment]
> Although ZB-GW04 has similar hardware to Sonoff Zigbee 3.0 USB Dongle Plus, we cannot guarantee that our firmware can run normally on Sonoff’s dongle, so you can use Sonoff’s open firmware, we will not provide dedicated firmware for Sonoff support

Got it. Thanks.
