### ISSUE TITLE
Help updating to ncp-uart-sw_6.10.9_115200.ota

### ISSUE THREAD

**Issue by danieldabate** [xsp1989/zigbeeFirmware#50]
Hi! I have a ZB-GW03-V1.4 flashed with ESPHOME and I tried updating its Zigbee firmware to **ncp-uart-sw_6.10.9_115200.ota** without success. 

The update finishes fine, but after reboot neither Z2M nor ZHA are not able to communicate with the device. Flashing **ncp-uart-nsw_6.5.5_115200.ota** and **ncp-uart-sw_6.7.10_115200.ota** work fine, so right now I'm using the last one (seems to be the same version that it came with from the factory).

I'm not sure how to debug this or if there is anything I'm missing. Any guidance is welcome!

**Comment by xsp1989** [comment]
I have updated the firmware, please try the new firmware. If you have any questions, please give me feedback.

**Comment by danieldabate** [comment]
It worked now!! Thanks for your help. Just out of curiosity, what was wrong with the other file?
